Repository FowApps/IronHook, pull requests merged in 2021-08, with the labels that each got.

#8 📝 Changelog file created with gitmoji-changelog
  .gitmoji-changelogrc
  CHANGELOG.md
Labels: documentation

#10 📝 Badge links updated
  .github/fow.opensource.png
  README.md
Labels: documentation

#12 Update README.md
  README.md
Labels: change-request

#13 Documentation/sample doc
  samples/IronHook.Web/Docs/PostgreSql/Step1.md
  samples/IronHook.Web/Docs/PostgreSql/Step2.md
  samples/IronHook.Web/Docs/PostgreSql/Step3.md
  samples/IronHook.Web/Docs/PostgreSql/Step4.md
  samples/IronHook.Web/Docs/README.md
  samples/IronHook.Web/IronHook.Web.csproj
Labels: change-request

#15 ♻ [CHANGE REQUEST] Update README.md
  README.md
Labels: change-request, effort-0.5
