Repository FowApps/IronHook, pull requests merged in 2021-12, with the labels that each got.

#39 🔀 [MERGE] Merge from Master to Develop
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/coverage-dotnet.yml
Labels: effort-1, dependencies

#45 Structural Refactoring - .NET 6.0 & SqlServer
  .codeclimate.yml
  IronHook.sln
  README.md
  common.props
  samples/IronHook.Web/Controllers/CustomersController.cs
  samples/IronHook.Web/IronHook.Web.csproj
  samples/IronHook.Web/Startup.cs
  samples/IronHook.Web/appsettings.json
  samples/dotnet6/IronHook.Web/Controllers/HookController.cs
  samples/dotnet6/IronHook.Web/Dtos/CustomerRequestDto.cs
  samples/dotnet6/IronHook.Web/Dtos/HookDto.cs
  samples/dotnet6/IronHook.Web/Dtos/HookRequestDto.cs
  samples/dotnet6/IronHook.Web/EventNames.cs
  samples/dotnet6/IronHook.Web/IronHook.Web.csproj
  samples/dotnet6/IronHook.Web/Program.cs
  samples/dotnet6/IronHook.Web/Properties/launchSettings.json
  samples/dotnet6/IronHook.Web/appsettings.json
  src/IronHook.Core/Abstractions/IHookService.cs
  src/IronHook.Core/Concrete/DefaultHookService.cs
  src/IronHook.Core/Entities/HookRequest.cs
  src/IronHook.Core/IronHook.Core.csproj
  src/IronHook.EntityFrameworkCore.PostgreSql/Extensions/NpgsqlDbContextOptionsBuilderExtensions.cs
  src/IronHook.EntityFrameworkCore.PostgreSql/IronHook.EntityFrameworkCore.PostgreSql.csproj
  src/IronHook.EntityFrameworkCore.PostgreSql/IronHookCoreDbContextPostgreSqlFactory.cs
  src/IronHook.EntityFrameworkCore.PostgreSql/Migrations/20211207215052_Initial.Designer.cs
  src/IronHook.EntityFrameworkCore.PostgreSql/Migrations/20211207215052_Initial.cs
  src/IronHook.EntityFrameworkCore.PostgreSql/Migrations/IronHookCoreDbContextModelSnapshot.cs
  src/IronHook.EntityFrameworkCore.PostgreSql/anchor.png
  src/IronHook.EntityFrameworkCore.SqlServer/Extensions/SqlServerDbContextOptionsBuilderExtensions.cs
  src/IronHook.EntityFrameworkCore.SqlServer/IronHook.EntityFrameworkCore.SqlServer.csproj
  src/IronHook.EntityFrameworkCore.SqlServer/IronHookCoreDbContextSqlServerFactory.cs
  src/IronHook.EntityFrameworkCore.SqlServer/Migrations/20211207222118_Initial.Designer.cs
  src/IronHook.EntityFrameworkCore.SqlServer/Migrations/20211207222118_Initial.cs
  src/IronHook.EntityFrameworkCore.SqlServer/Migrations/IronHookCoreDbContextModelSnapshot.cs
  src/IronHook.EntityFrameworkCore.SqlServer/anchor.png
  src/IronHook.EntityFrameworkCore/Extensions/ApplicationBuilderExtension.cs
  src/IronHook.EntityFrameworkCore/Extensions/ServiceCollectionExtension.cs
  src/IronHook.EntityFrameworkCore/IronHook.EntityFrameworkCore.csproj
  src/IronHook.EntityFrameworkCore/IronHookConsts.cs
  src/IronHook.EntityFrameworkCore/IronHookCoreDbContext.cs
  src/IronHook.EntityFrameworkCore/Properties/launchSettings.json
  src/IronHook.PostgreSql/Context/DesignTimeDbContext.cs
  src/IronHook.PostgreSql/Context/IronHookPostgreSqlDbContext.cs
  src/IronHook.PostgreSql/Extensions/ApplicationBuilderExtension.cs
  src/IronHook.PostgreSql/IronHook.PostgreSql.csproj
Labels: documentation, enhancement, priority:high, priority:medium, infrastructure, backlog, change-request, dev-ops, effort-8, effort-12, dependencies, codeclimate, quality, github_actions

#50 🎉 [FEATURE] Update versioning and package
  IronHook.sln
  README.md
  common.props
  samples/IronHook.Web/Startup.cs
  samples/dotnet6/IronHook.Web/Program.cs
  src/IronHook.Core/Concrete/DefaultHookService.cs
  src/IronHook.EntityFrameworkCore.PostgreSql/Extensions/NpgsqlDbContextOptionsBuilderExtensions.cs
  src/IronHook.EntityFrameworkCore.PostgreSql/IronHook.EntityFrameworkCore.PostgreSql.csproj
  src/IronHook.EntityFrameworkCore.SqlServer/IronHook.EntityFrameworkCore.SqlServer.csproj
  src/IronHook.EntityFrameworkCore/Extensions/ApplicationBuilderExtension.cs
  src/IronHook.EntityFrameworkCore/Extensions/ServiceCollectionExtension.cs
  src/IronHook.EntityFrameworkCore/IronHook.EntityFrameworkCore.csproj
  src/IronHook.EntityFrameworkCore/Properties/launchSettings.json
Labels: backlog, dependencies

#54 🐛[FIX] Fixed CI build
  Dockerfile
Labels: devops, priority:high, backlog, dev-ops, effort-1, dependencies, .NET, github_actions

#55 💚 Added docker file
  Dockerfile
  README.md
  samples/dotnet6/IronHook.Web/IronHook.Web.csproj
  samples/dotnet6/IronHook.Web/Properties/launchSettings.json
Labels: devops, dev-ops, .NET, github_actions
